### ISSUE TITLE
Error on calling client.read()

### ISSUE THREAD

**Issue by nasoma** [andreffs18/sheetsu-python#5]
There's a an error when calling the client.read function: TypeError: the JSON object must be str, not 'bytes'

**Comment by andreffs18** [comment]
Hey @nasoma , I'll take a look @ this later today.

**Comment by andreffs18** [comment]
How are you making that request? I've just tried the `read()` and it worked like charm 

```python
>>> from sheetsu import SheetsuClient
>>> ss_id = "<sheetsu_ss_id>"
>>> client = SheetsuClient(ss_id)
>>> client.read()
[{u'score': u'42', u'id': u'1', u'name': u'Peter'}, {u'score': u'89', u'id': u'2', u'name': u'Lois'}, {u'score': u'10', u'id': u'3', u'name': u'Meg'}, {u'score': u'42', u'id': u'4', u'name': u'Chris'}]
>>> 
```

**Comment by andreffs18** [comment]
@nasoma  is this still happening? If now I'll close this issue for now
